-- MartCart bulk catalog: exactly 2,500 products across 25 categories.
-- Safe to rerun: removes only rows generated by this seed (slug prefix bulk25-).
begin;

insert into public.categories (name, slug) values
  ('Electronics', 'electronics'),
  ('Fashion', 'fashion'),
  ('Footwear', 'footwear'),
  ('Home & Kitchen', 'home-and-kitchen'),
  ('Beauty', 'beauty'),
  ('Watches', 'watches'),
  ('Travel', 'travel'),
  ('Sports & Fitness', 'sports-and-fitness'),
  ('Outdoor & Camping', 'outdoor-and-camping'),
  ('Automotive', 'automotive'),
  ('Phones & Accessories', 'phones-and-accessories'),
  ('Computers & Accessories', 'computers-and-accessories'),
  ('Gaming', 'gaming'),
  ('Audio & Music', 'audio-and-music'),
  ('Cameras & Photography', 'cameras-and-photography'),
  ('Office Supplies', 'office-supplies'),
  ('Furniture', 'furniture'),
  ('Jewelry & Accessories', 'jewelry-and-accessories'),
  ('Kids & Toys', 'kids-and-toys'),
  ('Baby Products', 'baby-products'),
  ('Pet Supplies', 'pet-supplies'),
  ('Garden & Tools', 'garden-and-tools'),
  ('Health & Wellness', 'health-and-wellness'),
  ('Groceries & Pantry', 'groceries-and-pantry'),
  ('Lighting & Decor', 'lighting-and-decor')
on conflict (slug) do nothing;

delete from public.products where slug like 'bulk25-%';

with category_data(name, slug, category_no) as (values
  ('Electronics', 'electronics', 1),
  ('Fashion', 'fashion', 2),
  ('Footwear', 'footwear', 3),
  ('Home & Kitchen', 'home-and-kitchen', 4),
  ('Beauty', 'beauty', 5),
  ('Watches', 'watches', 6),
  ('Travel', 'travel', 7),
  ('Sports & Fitness', 'sports-and-fitness', 8),
  ('Outdoor & Camping', 'outdoor-and-camping', 9),
  ('Automotive', 'automotive', 10),
  ('Phones & Accessories', 'phones-and-accessories', 11),
  ('Computers & Accessories', 'computers-and-accessories', 12),
  ('Gaming', 'gaming', 13),
  ('Audio & Music', 'audio-and-music', 14),
  ('Cameras & Photography', 'cameras-and-photography', 15),
  ('Office Supplies', 'office-supplies', 16),
  ('Furniture', 'furniture', 17),
  ('Jewelry & Accessories', 'jewelry-and-accessories', 18),
  ('Kids & Toys', 'kids-and-toys', 19),
  ('Baby Products', 'baby-products', 20),
  ('Pet Supplies', 'pet-supplies', 21),
  ('Garden & Tools', 'garden-and-tools', 22),
  ('Health & Wellness', 'health-and-wellness', 23),
  ('Groceries & Pantry', 'groceries-and-pantry', 24),
  ('Lighting & Decor', 'lighting-and-decor', 25)
),
product_types(category_name, type_no, product_type) as (values
  ('Electronics', 1, 'Bluetooth Speakers'), ('Electronics', 2, 'Wireless Chargers'), ('Electronics', 3, 'Smart Plugs'), ('Electronics', 4, 'USB Hubs'), ('Electronics', 5, 'Portable Projectors'), ('Electronics', 6, 'Streaming Devices'), ('Electronics', 7, 'E-Readers'), ('Electronics', 8, 'Power Banks'), ('Electronics', 9, 'Smart Sensors'), ('Electronics', 10, 'Mini Keyboards'),
  ('Fashion', 1, 'T-Shirts'), ('Fashion', 2, 'Hoodies'), ('Fashion', 3, 'Jeans'), ('Fashion', 4, 'Chinos'), ('Fashion', 5, 'Dresses'), ('Fashion', 6, 'Jackets'), ('Fashion', 7, 'Sweaters'), ('Fashion', 8, 'Polo Shirts'), ('Fashion', 9, 'Shorts'), ('Fashion', 10, 'Skirts'),
  ('Footwear', 1, 'Running Shoes'), ('Footwear', 2, 'Sneakers'), ('Footwear', 3, 'Loafers'), ('Footwear', 4, 'Boots'), ('Footwear', 5, 'Sandals'), ('Footwear', 6, 'Slides'), ('Footwear', 7, 'Hiking Shoes'), ('Footwear', 8, 'Canvas Shoes'), ('Footwear', 9, 'Formal Shoes'), ('Footwear', 10, 'House Slippers'),
  ('Home & Kitchen', 1, 'Cookware Sets'), ('Home & Kitchen', 2, 'Dinnerware Sets'), ('Home & Kitchen', 3, 'Storage Baskets'), ('Home & Kitchen', 4, 'Water Bottles'), ('Home & Kitchen', 5, 'Coffee Makers'), ('Home & Kitchen', 6, 'Air Fryers'), ('Home & Kitchen', 7, 'Knife Sets'), ('Home & Kitchen', 8, 'Food Containers'), ('Home & Kitchen', 9, 'Throw Pillows'), ('Home & Kitchen', 10, 'Kitchen Organizers'),
  ('Beauty', 1, 'Face Cleansers'), ('Beauty', 2, 'Moisturizers'), ('Beauty', 3, 'Hair Oils'), ('Beauty', 4, 'Body Lotions'), ('Beauty', 5, 'Shampoo'), ('Beauty', 6, 'Conditioners'), ('Beauty', 7, 'Lip Balms'), ('Beauty', 8, 'Makeup Brushes'), ('Beauty', 9, 'Perfume Mists'), ('Beauty', 10, 'Bath Sets'),
  ('Watches', 1, 'Chronograph Watches'), ('Watches', 2, 'Digital Watches'), ('Watches', 3, 'Dress Watches'), ('Watches', 4, 'Field Watches'), ('Watches', 5, 'Sports Watches'), ('Watches', 6, 'Minimal Watches'), ('Watches', 7, 'Diving Watches'), ('Watches', 8, 'Smartwatches'), ('Watches', 9, 'Automatic Watches'), ('Watches', 10, 'Travel Watches'),
  ('Travel', 1, 'Carry-On Bags'), ('Travel', 2, 'Travel Backpacks'), ('Travel', 3, 'Packing Cubes'), ('Travel', 4, 'Passport Holders'), ('Travel', 5, 'Neck Pillows'), ('Travel', 6, 'Luggage Straps'), ('Travel', 7, 'Toiletry Bags'), ('Travel', 8, 'Travel Adapters'), ('Travel', 9, 'Duffel Bags'), ('Travel', 10, 'Shoe Bags'),
  ('Sports & Fitness', 1, 'Yoga Mats'), ('Sports & Fitness', 2, 'Resistance Bands'), ('Sports & Fitness', 3, 'Training Gloves'), ('Sports & Fitness', 4, 'Skipping Ropes'), ('Sports & Fitness', 5, 'Foam Rollers'), ('Sports & Fitness', 6, 'Gym Bags'), ('Sports & Fitness', 7, 'Water Bottles'), ('Sports & Fitness', 8, 'Fitness Trackers'), ('Sports & Fitness', 9, 'Balance Boards'), ('Sports & Fitness', 10, 'Workout Towels'),
  ('Outdoor & Camping', 1, 'Camping Tents'), ('Outdoor & Camping', 2, 'Sleeping Bags'), ('Outdoor & Camping', 3, 'Camping Chairs'), ('Outdoor & Camping', 4, 'Lanterns'), ('Outdoor & Camping', 5, 'Cooler Bags'), ('Outdoor & Camping', 6, 'Hammocks'), ('Outdoor & Camping', 7, 'Trekking Poles'), ('Outdoor & Camping', 8, 'Camp Tables'), ('Outdoor & Camping', 9, 'Headlamps'), ('Outdoor & Camping', 10, 'Picnic Blankets'),
  ('Automotive', 1, 'Car Chargers'), ('Automotive', 2, 'Seat Organizers'), ('Automotive', 3, 'Phone Mounts'), ('Automotive', 4, 'Floor Mats'), ('Automotive', 5, 'Cleaning Kits'), ('Automotive', 6, 'Emergency Kits'), ('Automotive', 7, 'Sun Shades'), ('Automotive', 8, 'Tire Gauges'), ('Automotive', 9, 'Trunk Organizers'), ('Automotive', 10, 'Car Covers'),
  ('Phones & Accessories', 1, 'Phone Cases'), ('Phones & Accessories', 2, 'Screen Protectors'), ('Phones & Accessories', 3, 'Camera Lenses'), ('Phones & Accessories', 4, 'Selfie Sticks'), ('Phones & Accessories', 5, 'Phone Stands'), ('Phones & Accessories', 6, 'Wireless Earbuds'), ('Phones & Accessories', 7, 'Charging Cables'), ('Phones & Accessories', 8, 'SIM Tool Kits'), ('Phones & Accessories', 9, 'Grip Holders'), ('Phones & Accessories', 10, 'Car Mounts'),
  ('Computers & Accessories', 1, 'Laptop Stands'), ('Computers & Accessories', 2, 'Mechanical Keyboards'), ('Computers & Accessories', 3, 'Wireless Mice'), ('Computers & Accessories', 4, 'Webcams'), ('Computers & Accessories', 5, 'USB Microphones'), ('Computers & Accessories', 6, 'Laptop Sleeves'), ('Computers & Accessories', 7, 'Docking Stations'), ('Computers & Accessories', 8, 'Monitor Arms'), ('Computers & Accessories', 9, 'Cooling Pads'), ('Computers & Accessories', 10, 'Desk Mats'),
  ('Gaming', 1, 'Gaming Headsets'), ('Gaming', 2, 'Game Controllers'), ('Gaming', 3, 'Gaming Mice'), ('Gaming', 4, 'RGB Keyboards'), ('Gaming', 5, 'Controller Stands'), ('Gaming', 6, 'Capture Cards'), ('Gaming', 7, 'Gaming Chairs'), ('Gaming', 8, 'Mouse Pads'), ('Gaming', 9, 'Console Cases'), ('Gaming', 10, 'Streaming Lights'),
  ('Audio & Music', 1, 'Studio Headphones'), ('Audio & Music', 2, 'Bluetooth Earphones'), ('Audio & Music', 3, 'Podcast Microphones'), ('Audio & Music', 4, 'Audio Interfaces'), ('Audio & Music', 5, 'MIDI Controllers'), ('Audio & Music', 6, 'Speaker Stands'), ('Audio & Music', 7, 'XLR Cables'), ('Audio & Music', 8, 'Mixing Headphones'), ('Audio & Music', 9, 'USB Microphones'), ('Audio & Music', 10, 'Music Stands'),
  ('Cameras & Photography', 1, 'Camera Bags'), ('Cameras & Photography', 2, 'Tripods'), ('Cameras & Photography', 3, 'LED Panels'), ('Cameras & Photography', 4, 'Camera Straps'), ('Cameras & Photography', 5, 'Memory Card Cases'), ('Cameras & Photography', 6, 'Lens Cleaning Kits'), ('Cameras & Photography', 7, 'Remote Shutters'), ('Cameras & Photography', 8, 'Reflectors'), ('Cameras & Photography', 9, 'Camera Backpacks'), ('Cameras & Photography', 10, 'Photo Backgrounds'),
  ('Office Supplies', 1, 'Notebooks'), ('Office Supplies', 2, 'Ballpoint Pens'), ('Office Supplies', 3, 'Desk Organizers'), ('Office Supplies', 4, 'Staplers'), ('Office Supplies', 5, 'Document Folders'), ('Office Supplies', 6, 'File Boxes'), ('Office Supplies', 7, 'Sticky Notes'), ('Office Supplies', 8, 'Whiteboards'), ('Office Supplies', 9, 'Calculator Sets'), ('Office Supplies', 10, 'Paper Trays'),
  ('Furniture', 1, 'Office Chairs'), ('Furniture', 2, 'Writing Desks'), ('Furniture', 3, 'Bookshelves'), ('Furniture', 4, 'Side Tables'), ('Furniture', 5, 'Bedside Cabinets'), ('Furniture', 6, 'TV Stands'), ('Furniture', 7, 'Storage Benches'), ('Furniture', 8, 'Dining Chairs'), ('Furniture', 9, 'Coffee Tables'), ('Furniture', 10, 'Console Tables'),
  ('Jewelry & Accessories', 1, 'Necklaces'), ('Jewelry & Accessories', 2, 'Bracelets'), ('Jewelry & Accessories', 3, 'Earrings'), ('Jewelry & Accessories', 4, 'Rings'), ('Jewelry & Accessories', 5, 'Cufflinks'), ('Jewelry & Accessories', 6, 'Brooches'), ('Jewelry & Accessories', 7, 'Hair Clips'), ('Jewelry & Accessories', 8, 'Sunglasses'), ('Jewelry & Accessories', 9, 'Wallets'), ('Jewelry & Accessories', 10, 'Belts'),
  ('Kids & Toys', 1, 'Building Blocks'), ('Kids & Toys', 2, 'Puzzle Sets'), ('Kids & Toys', 3, 'Plush Toys'), ('Kids & Toys', 4, 'Art Kits'), ('Kids & Toys', 5, 'Remote Cars'), ('Kids & Toys', 6, 'Board Games'), ('Kids & Toys', 7, 'Science Kits'), ('Kids & Toys', 8, 'Doll Sets'), ('Kids & Toys', 9, 'Outdoor Toys'), ('Kids & Toys', 10, 'Learning Cards'),
  ('Baby Products', 1, 'Baby Blankets'), ('Baby Products', 2, 'Feeding Sets'), ('Baby Products', 3, 'Bib Sets'), ('Baby Products', 4, 'Diaper Bags'), ('Baby Products', 5, 'Baby Towels'), ('Baby Products', 6, 'Bottle Warmers'), ('Baby Products', 7, 'Changing Mats'), ('Baby Products', 8, 'Swaddle Sets'), ('Baby Products', 9, 'Baby Monitors'), ('Baby Products', 10, 'Nursery Organizers'),
  ('Pet Supplies', 1, 'Pet Beds'), ('Pet Supplies', 2, 'Dog Collars'), ('Pet Supplies', 3, 'Cat Toys'), ('Pet Supplies', 4, 'Feeding Bowls'), ('Pet Supplies', 5, 'Grooming Brushes'), ('Pet Supplies', 6, 'Leashes'), ('Pet Supplies', 7, 'Pet Carriers'), ('Pet Supplies', 8, 'Training Pads'), ('Pet Supplies', 9, 'Aquarium Accessories'), ('Pet Supplies', 10, 'Pet Blankets'),
  ('Garden & Tools', 1, 'Hand Tool Sets'), ('Garden & Tools', 2, 'Pruning Shears'), ('Garden & Tools', 3, 'Garden Gloves'), ('Garden & Tools', 4, 'Plant Pots'), ('Garden & Tools', 5, 'Watering Cans'), ('Garden & Tools', 6, 'Garden Hoses'), ('Garden & Tools', 7, 'Tool Boxes'), ('Garden & Tools', 8, 'Drill Bits'), ('Garden & Tools', 9, 'Measuring Tools'), ('Garden & Tools', 10, 'Work Lights'),
  ('Health & Wellness', 1, 'Massage Rollers'), ('Health & Wellness', 2, 'Sleep Masks'), ('Health & Wellness', 3, 'Aromatherapy Diffusers'), ('Health & Wellness', 4, 'Reusable Ice Packs'), ('Health & Wellness', 5, 'Posture Supports'), ('Health & Wellness', 6, 'Pill Organizers'), ('Health & Wellness', 7, 'Heating Pads'), ('Health & Wellness', 8, 'Exercise Bands'), ('Health & Wellness', 9, 'Wellness Journals'), ('Health & Wellness', 10, 'Water Filters'),
  ('Groceries & Pantry', 1, 'Coffee Beans'), ('Groceries & Pantry', 2, 'Tea Blends'), ('Groceries & Pantry', 3, 'Granola Packs'), ('Groceries & Pantry', 4, 'Pasta Packs'), ('Groceries & Pantry', 5, 'Spice Sets'), ('Groceries & Pantry', 6, 'Cooking Oils'), ('Groceries & Pantry', 7, 'Snack Boxes'), ('Groceries & Pantry', 8, 'Cereal Packs'), ('Groceries & Pantry', 9, 'Baking Mixes'), ('Groceries & Pantry', 10, 'Dried Fruit'),
  ('Lighting & Decor', 1, 'Table Lamps'), ('Lighting & Decor', 2, 'Floor Lamps'), ('Lighting & Decor', 3, 'Wall Mirrors'), ('Lighting & Decor', 4, 'Decorative Vases'), ('Lighting & Decor', 5, 'Wall Clocks'), ('Lighting & Decor', 6, 'String Lights'), ('Lighting & Decor', 7, 'Candle Holders'), ('Lighting & Decor', 8, 'Photo Frames'), ('Lighting & Decor', 9, 'Desk Lamps'), ('Lighting & Decor', 10, 'Accent Lights')
),
modifiers(mod_no, modifier) as (values
  (1, 'Core'), (2, 'Select'), (3, 'Plus'), (4, 'Pro'), (5, 'Elite'), (6, 'Prime'), (7, 'Flex'), (8, 'Studio'), (9, 'Max'), (10, 'Signature')
),
generated as (
select
  'bulk25-' || c.slug || '-' || lpad(pt.type_no::text,2,'0') || '-' || lpad(m.mod_no::text,2,'0') as slug,
  c.name || ' — ' || m.modifier || ' ' || pt.product_type as name,
  'A carefully selected ' || lower(m.modifier) || ' ' || lower(pt.product_type) || ' from the ' || c.name || ' collection.' as description,
  round((12 + ((c.category_no * 37 + pt.type_no * 19 + m.mod_no * 11) % 2400) / 10.0)::numeric, 2) as price,
  'USD' as currency,
  (20 + ((c.category_no * 71 + pt.type_no * 29 + m.mod_no * 17) % 181))::int as stock_quantity,
  true as is_active,
  'MartCart ' || left(regexp_replace(c.name, '[^A-Za-z0-9]', '', 'g'), 12) || ' ' || m.modifier as brand,
  round((4.0 + ((c.category_no + pt.type_no + m.mod_no) % 11) / 10.0)::numeric, 2) as rating,
  (8 + ((c.category_no * 13 + pt.type_no * 7 + m.mod_no * 5) % 193))::int as review_count,
  c.slug as category_slug
from category_data c
join product_types pt on pt.category_name = c.name
cross join modifiers m
)
insert into public.products
  (name, slug, description, price, currency, main_image_url, stock_quantity, is_active, brand, rating, review_count, category_id)
select
  g.name, g.slug, g.description, g.price, g.currency, null, g.stock_quantity, g.is_active,
  g.brand, g.rating, g.review_count, c.id
from generated g
join public.categories c on c.slug = g.category_slug
where not exists (select 1 from public.products p where p.slug = g.slug);

-- Guardrail: the seed must create exactly 2,500 generated products.
do $$
declare n integer;
begin
  select count(*) into n from public.products where slug like 'bulk25-%';
  if n <> 2500 then raise exception 'MartCart bulk seed expected 2500 products, found %', n; end if;
end $$;
commit;
